spring:
  application:
    name: restaurant

  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog-master.yml

  zipkin:
    base-url: http://localhost:9411

restaurant:
  tracing:
    sql:
      enabled: true

keycloak:
  realm: online_shop
  resource: client_back
  auth-server-url: http://localhost:8180/auth
  bearer-only: true
  principal-attribute: preferred_username
